Ghigha_store/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (isset(Auth::user()->name)) {
        return redirect()->route('admin.home');
    } else {
        return redirect()->route('home');
    }
});

Auth::routes();

Route::get('/home', 'Front\FrontController@index')->name('home');
Route::get('/detail/{id}', 'Front\FrontController@detailProduk')->name('detail');
Route::get('/produk/{search?}', 'Front\FrontController@produk')->name('produk');

// get produk by kategori
Route::get('/produk/get_produk/{kategori_id}', 'Admin\ProdukController@getProduk');
Route::get('/getImageMore/{produk_id}', 'Admin\ProdukController@getImageMore')->name('getImageMore');


Route::group(['middleware' => 'auth'], function () {
    Route::get('/admin', 'Admin\AdminController@index');
    Route::name('admin.')->group(function () {
        Route::get('/admin/home', 'Admin\AdminController@home')->name('home');
        Route::get('/admin/detail_produk', 'Admin\AdminController@detail_produk')->name('detail_produk');
        Route::get('/admin/produk', 'Admin\AdminController@produk')->name('produk');
        Route::get('/admin/setting', 'Admin\AdminController@setting')->name('setting');

        // Img More
        Route::get('/admin/form/img_more/{produk_id}', 'Admin\ProdukController@img_more')->name('form.img_more');
        Route::post('/admin/form/img_more/store', 'Admin\ProdukController@store_img_more')->name('form.img_more.store');
        Route::get('/admin/form/img_more/del/{id}/{produk_id}', 'Admin\ProdukController@del_img_more')->name('form.img_more.del');

        // Form
        // why
        Route::get('/admin/form/why', 'Admin\FormController@form_why')->name('form.why');
        Route::get('/admin/form/{page}', 'Admin\FormController@index')->name('form');
        Route::post('/admin/form/store/{page}', 'Admin\FormController@store')->name('form.store');
        Route::get('/admin/form/edit/{page}/{id}', 'Admin\FormController@edit')->name('form.edit');
        Route::post('/admin/form/update/{page}/{id}', 'Admin\FormController@update')->name('form.update');
        Route::post('/admin/form/why/store', 'Admin\FormController@store_kelebihan')->name('form.why.store');
        Route::get('/admin/form/delete/{page}/{id}', 'Admin\FormController@delete')->name('form.delete');

        // Populer produk
        Route::get('/admin/produk/populer/{id}', 'Admin\ProdukController@store_populer')->name('produk.populer');
        Route::get('/admin/produk/populer/delete/{id}', 'Admin\ProdukController@delete_populer')->name('produk.populer.delete');

        // Produk
        Route::get('/admin/produk/detail/{id}', 'Admin\ProdukController@detail')->name('produk.detail');
        Route::get('/admin/form/produk/form_produk', 'Admin\ProdukController@index')->name('form.produk.form_produk');
        Route::get('/admin/form/produk/form_edit/{id}', 'Admin\ProdukController@form_edit')->name('form.produk.form_edit');
        Route::post('/admin/form/produk/store', 'Admin\ProdukController@store')->name('form.produk.store');
        Route::post('/admin/form/produk/edit/{id}', 'Admin\ProdukController@proses_edit')->name('form.produk.edit');
        Route::get('/admin/form/produk/delete/{id}', 'Admin\ProdukController@delete')->name('form.produk.delete');


        // Setting
        Route::post('/admin/setting/store_nohp', 'Admin\SettingController@store_nohp')->name('setting.store_nohp');
        Route::post('/admin/setting/store_kategori', 'Admin\SettingController@store_kategori')->name('setting.store_kategori');
        Route::post('/admin/setting/edit_kategori/{id}', 'Admin\SettingController@edit_kategori')->name('setting.edit_kategori');
        Route::get('/admin/setting/hapus_kategori/{id}', 'Admin\SettingController@hapus_kategori')->name('setting.hapus_kategori');
        Route::post('/admin/setting/store_alamat', 'Admin\SettingController@store_alamat')->name('setting.store_alamat');
        Route::post('/admin/setting/store_sosmed', 'Admin\SettingController@store_sosmed')->name('setting.store_sosmed');
    });
});

Ghigha_store/app/Http/Controllers/Admin/FormController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Banner;
use App\Galeri;
use App\Http\Controllers\Controller;
use App\Kelebihan;
use App\Populer_produk;
use App\Produk;
use App\Testimoni;
use App\Video;
use Illuminate\Support\Facades\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Crypt;

class FormController extends Controller
{
    // Catatan page nomber
    // 1 banner         4 testimoni
    // 2 terpopuler     5 video produk
    // 3 galeri

    private function cekPage($page)
    {
        if ($page == '1') {
            $form_title = 'Banner';
            $thumbnail = 'on';
            $title = 'on';
            $deskripsi = 'off';
            $path = 'storage/thumbnails_banner';
        } else if ($page == '2') {
            $form_title = 'Terpopuler';
            $thumbnail = 'off';
            $title = 'off';
            $deskripsi = 'off';
            $path = '';
        } else if ($page == '3') {
            $form_title = 'Galeri';
            $thumbnail = 'on';
            $title = 'on';
            $deskripsi = 'on';
            $path = 'storage/thumbnails_galeri';
        } else if ($page == '4') {
            $form_title = 'Testimoni';
            $thumbnail = 'on';
            $title = 'on';
            $deskripsi = 'off';
            $path = 'storage/thumbnails_testimoni';
        } else {
            $form_title = 'Video';
            $thumbnail = 'off';
            $title = 'off';
            $deskripsi = 'off';
            $data['video'] = 'on';
            $path = 'storage/video';
        }

        $data['form_title'] = $form_title;
        $data['thumbnail'] = $thumbnail;
        $data['title'] = $title;
        $data['deskripsi'] = $deskripsi;
        $data['path'] = $path;

        return $data;
    }

    public function index($page)
    {
        $page = Crypt::decrypt($page);

        $data['page'] = $page;

        $cekPage = $this->cekPage($page);

        $data['form_title'] = $cekPage['form_title'];
        $data['thumbnail'] = $cekPage['thumbnail'];
        $data['title'] = $cekPage['title'];
        $data['deskripsi'] = $cekPage['deskripsi'];
        $data['produk'] = Produk::all();
        if (isset($cekPage['video'])) {
            $data['video'] = $cekPage['video'];
        }

        return view('admin.form.index', $data);
    }

    public function store(Request $request, $page)
    {
        $page = Crypt::decrypt($page);

        $cekPage = $this->cekPage($page);

        if ($request->file() != null) {
            $file = $request->file('thumbnail');

            $tujuan_upload = $cekPage['path'];
            $file->move($tujuan_upload, time() . $file->getClientOriginalName());
            $file = $tujuan_upload . '/' . time() . $file->getClientOriginalName();
        } else {
            $file = '';
        }



        $obj['thumbnail'] = $file;
        $obj['title'] = $request->title;
        if (isset($request->deskripsi)) {
            $obj['deskripsi'] = $request->deskripsi;
        }

        $this->insertToTable($page, $obj);
        // Clear cahce 
        Artisan::call('cache:clear');
        if ($page <= 3) {
            return redirect()->route('admin.home')->with('success', 'Berhasil tambah data');
        } else {
            return redirect()->route('admin.detail_produk')->with('success', 'Berhasil tambah data');
        }
    }

    public function edit($page, $id)
    {
        $page = Crypt::decrypt($page);
        $id = Crypt::decrypt($id);
        $cekPage = $this->cekPage($page);
        if ($page == 1) {
            $update = Banner::find($id);
        } else if ($page == 3) {
            $update = Galeri::find($id);
        }

        $data['form_title'] = $cekPage['form_title'];
        $data['thumbnail'] = $cekPage['thumbnail'];
        $data['title'] = $cekPage['title'];
        $data['deskripsi'] = $cekPage['deskripsi'];
        $data['produk'] = Produk::all();
        if (isset($cekPage['video'])) {
            $data['video'] = $cekPage['video'];
        }
        $data['data'] = $update;
        $data['page'] = $page;

        return view('admin.form.form_edit', $data);
    }

    public function update(Request $request, $page, $id)
    {
        $page = Crypt::decrypt($page);
        $id = Crypt::decrypt($id);
        if ($page == 1) {
            $update = Banner::find($id);
        } else if ($page == 3) {
            $update = Galeri::find($id);
        }

        $cekPage = $this->cekPage($page);

        if ($request->file() != null) {
            $file = $request->file('thumbnail');

            $tujuan_upload = $cekPage['path'];
            $file->move($tujuan_upload, time() . $file->getClientOriginalName());
            $file = $tujuan_upload . '/' . time() . $file->getClientOriginalName();
            $obj['thumbnail'] = $file;
            File::delete($update->thumbnail);
        }

        $obj['title'] = $request->title;
        if (isset($request->request)) {
            $obj['deskripsi'] = $request->deskripsi;
        }

        $update->update($obj);
        Artisan::call('cache:clear');
        if ($page <= 3) {
            return redirect()->route('admin.home')->with('success', 'Berhasil update data');
        } else {
            return redirect()->route('admin.detail_produk')->with('success', 'Berhasil update data');
        }
    }

    public function delete($page, $id)
    {
        $page = Crypt::decrypt($page);
        $id = Crypt::decrypt($id);

        if ($page == '1') {
            $delete = Banner::find($id);
        } else if ($page == '2') {
            $delete = '';
        } else if ($page == '3') {
            $delete = Galeri::find($id);
        } else if ($page == '4') {
            $delete = Testimoni::find($id);
        } else {
            $delete = Video::find($id);
        }

        File::delete($delete->thumbnail);
        $delete->delete();
        // Clear cahce 
        Artisan::call('cache:clear');
        if ($page <= 3) {
            return redirect()->route('admin.home')->with('success', 'Berhasil di hapus');
        } else {
            return redirect()->route('admin.detail_produk')->with('success', 'Berhasil di hapus');
        }
    }

    private function insertToTable($page, $obj)
    {
        if ($page == '1') {
            Banner::insert($obj);
        } else if ($page == '2') {
            $form_title = 'Terpopuler';
            $thumbnail = 'off';
            $title = 'off';
            $deskripsi = 'off';
        } else if ($page == '3') {
            Galeri::insert($obj);
        } else if ($page == '4') {
            Testimoni::insert($obj);
        } else {
            Video::insert($obj);
        }
    }

    public function form_why()
    {
        $data['kelebihan'] = Kelebihan::first();
        return view('admin.form.form_why', $data);
    }

    public function store_kelebihan(Request $request)
    {
        $kelebihan = Kelebihan::first();

        $obj['kelebihan'] = $request->kelebihan;

        if ($kelebihan == []) {
            Kelebihan::insert($obj);
            $msg = 'Berhasil insert kelebihan';
        } else {
            $kelebihan->update($obj);
            $msg = 'Berhasil update kelebihan';
        }
        return redirect()->route('admin.detail_produk')->with('success', $msg);
    }
}

Ghigha_store/resources/views/admin/form/form_edit.blade.php
@extends('layouts.admin_template')
@section('content')
<div class="container-fluid pt-4 mb-4">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="card shadow-lg">
                <div class="card-header bg-primary small text-white">{{ $form_title }}</div>
                <div class="card-body">
                    <form action="{{ route('admin.form.update', [Crypt::encrypt($page), Crypt::encrypt($data->id)]) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-img form-group text-center">
                            <?php if (!isset($video)) { ?>
                                <div class="border rounded text-center img-canvas border-0">
                                    <img src="{{ asset($data->thumbnail) }}" alt="" class="img-output" style="opacity: 1 !important;">
                                </div>
                            <?php } ?>
                            <input type="file" name="thumbnail" id="imageUpload" style="display: <?php if (isset($video)) { ?> block <?php } else { ?> none <?php } ?>;" class="form-control">
                            <?php if (!isset($video)) { ?>
                                <label class="btn juna-my-button mb-4" for="imageUpload" aria-describedby="inputGroupFileAddon02" style="margin-top: 2rem;">Choose File</label>
                            <?php } ?>
                        </div>
                        <div class="form-group">
                            @if($page == 1)
                            <small class="float-left title-url"></small>
                            <a href="#" class="badge badge-warning rounded float-right mb-3" data-toggle="modal" data-target="#modal-url">URL Produk</a>
                            @endif
                            <input type="text" name="title" id="title" class="form-control" <?php if ($page == 1) echo 'readonly' ?> value="{{ $data->title }}" required placeholder="@if($page != 1) Title @else URL @endif">
                        </div>
                        @if($deskripsi == 'on')
                        <div class="form-group">
                            <textarea class="form-control" id="deskripsi" name="deskripsi" placeholder="Masukan Deskripsi">{{ $data->deskripsi }}</textarea>
                        </div>
                        @endif
                        <div class="form-group text-right">
                            <button class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('modal')
<!-- url -->
<div class="modal fade" id="modal-url">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title small"><strong>Tambah url</strong></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-0">
                <table class="table table-striped table-content-middle">
                    <thead>
                        <tr>
                            <th>Thumbnail</th>
                            <th>Nama</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($produk as $val)
                        <tr>
                            <td><img src="{{ asset($val->thumbnail) }}" alt="thumbnail" class="img-banner-data"></td>
                            <td>{{ $val->nama }}</td>
                            <td><a href="#" data-link="<?= route('detail', Illuminate\Support\Facades\Crypt::encrypt($val->id)) ?>" data-title="{{ $val->nama }}" class="badge badge-primary btn-add-url" data-dismiss="modal"><i class="fa fa-plus"></i> Tambah</a></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="modal-footer justify-content-between bg-primary">
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endsection

Ghigha_store/resources/views/admin/form/form_edit_produk.blade.php
@extends('layouts.admin_template')
@section('content')
<div class="container-fluid pt-4">
    <div class="row">
        <div class="col-lg-10 offset-lg-1">
            <div class="card shadow-lg">
                <div class="card-header bg-primary small text-white"></div>
                <div class="card-body">
                    <form action="{{ route('admin.form.produk.edit', Crypt::encrypt($produk->id)) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-img form-group text-center">
                            <div class="border rounded text-center img-canvas border-0">
                                <img src="{{ asset($produk->thumbnail) }}" alt="" class="img-output" style="opacity: 1 !important;">
                            </div>
                            <input type="file" name="thumbnail" id="imageUpload" style="display: none;" class="form-control">
                            <label class="btn juna-my-button mb-4" for="imageUpload" aria-describedby="inputGroupFileAddon02" style="margin-top: 2rem;">Choose File</label>
                        </div>
                        <div class="form-group">
                            <small>Nama</small>
                            <input type="text" name="nama" id="nama" class="form-control" value="{{ $produk->nama }}" required placeholder="...">
                        </div>
                        <div class="form-group">
                            <div class="container-fluid px-0">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <small>Harga</small>
                                        <input type="number" name="harga" id="harga" class="form-control" value="{{ $produk->harga }}" required placeholder="...">
                                    </div>
                                    <div class="col-lg-6">
                                        <small>Diskon</small>
                                        <input type="number" name="diskon" id="diskon" class="form-control" value="{{ $produk->diskon }}" placeholder="...">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <small>Kategori</small>
                            <select name="kategori_id" id="kategori_id" class="form-control">
                                <option value="{{ $produk->kategori->id }}">{{ $produk->kategori->kategori }}</option>
                                @foreach($kategori as $val)
                                @if($produk->kategori->id != $val->id)
                                <option value="{{ $val->id }}">{{ $val->kategori }}</option>
                                @endif
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <small>Promosi</small>
                            <textarea name="promosi" id="promosi" cols="30" rows="3" class="form-control" required placeholder="...">{{ $produk->promosi }}</textarea>
                        </div>
                        <div class="form-group">
                            <small>Deskripsi</small>
                            <textarea name="deskripsi" id="ckeditor" cols="30" rows="3" class="ckeditor" required placeholder="...">{!! $produk->deskripsi !!}</textarea>
                        </div>
                        <div class="form-group text-right">
                            <button class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Ghigha_store/resources/views/admin/form/form_img_more.blade.php
@extends('layouts.admin_template')
@section('content')
<div class="container-fluid pt-4">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="card shadow-lg">
                <div class="card-header bg-primary small text-white"></div>
                <div class="card-body">
                    <form action="{{ route('admin.form.img_more.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-img form-group text-center">
                            <div class="border rounded text-center img-canvas border-0">
                                <img src="" alt="" class="img-output" height="100%">
                            </div>
                            <input type="file" name="thumbnail" id="imageUpload" style="display:none" class="form-control">
                            <label class="btn juna-my-button mb-4" for="imageUpload" aria-describedby="inputGroupFileAddon02" style="margin-top: 2rem;">Choose File</label>
                        </div>
                        <input type="hidden" name="produk_id" value="{{ $produk_id }}">
                        <div class="form-group text-center">
                            <button class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Ghigha_store/resources/views/admin/form/form_produk.blade.php
@extends('layouts.admin_template')
@section('content')
<div class="container-fluid pt-4">
    <div class="row">
        <div class="col-lg-10 offset-lg-1">
            <div class="card shadow-lg">
                <div class="card-header bg-primary small text-white"></div>
                <div class="card-body">
                    <form action="{{ route('admin.form.produk.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-img form-group text-center">
                            <div class="border rounded text-center img-canvas border-0">
                                <img src="" alt="" class="img-output">
                            </div>
                            <input type="file" name="thumbnail" id="imageUpload" style="display: none;" class="form-control">
                            <label class="btn juna-my-button mb-4" for="imageUpload" aria-describedby="inputGroupFileAddon02" style="margin-top: 2rem;">Choose File</label>
                        </div>
                        <div class="form-group">
                            <small>Nama</small>
                            <input type="text" name="nama" id="nama" class="form-control" required placeholder="...">
                        </div>
                        <div class="form-group">
                            <div class="container-fluid px-0">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <small>Harga</small>
                                        <input type="number" name="harga" id="harga" class="form-control" required placeholder="...">
                                    </div>
                                    <div class="col-lg-6">
                                        <small>Diskon</small>
                                        <input type="number" name="diskon" id="diskon" class="form-control" placeholder="...">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <small>Kategori</small>
                            <select name="kategori_id" id="kategori_id" class="form-control">
                                @foreach($kategori as $val)
                                <option value="{{ $val->id }}">{{ $val->kategori }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <small>Promosi</small>
                            <textarea name="promosi" id="promosi" cols="30" rows="3" class="form-control" required placeholder="..."></textarea>
                        </div>
                        <div class="form-group">
                            <small>Deskripsi</small>
                            <textarea name="deskripsi" id="ckeditor" cols="30" rows="3" class="ckeditor" required placeholder="..."></textarea>
                        </div>
                        <div class="form-group text-right">
                            <button class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Ghigha_store/resources/views/admin/form/form_why.blade.php
@extends('layouts.admin_template')
@section('content')
<div class="container" style="padding-top: 2rem;">
    <small>Kenapa sih harus di <b>Ghigha Store</b> ?</small>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header bg-primary"></div>
                <div class="card-body">
                    <form action="{{ route('admin.form.why.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <textarea name="kelebihan" id="ckeditor" class="ckeditor">@if(isset($kelebihan)){!! $kelebihan->kelebihan !!}@endif</textarea>
                        </div>
                        <div class="form-group text-right">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Ghigha_store/resources/views/admin/form/index.blade.php
@extends('layouts.admin_template')
@section('content')
<div class="container-fluid pt-4 mb-4">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="card shadow-lg">
                <div class="card-header bg-primary small text-white">{{ $form_title }}</div>
                <div class="card-body">
                    <form action="{{ route('admin.form.store', Crypt::encrypt($page)) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-img form-group text-center">
                            <?php if (!isset($video)) { ?>
                                <div class="border rounded text-center img-canvas border-0">
                                    <img src="" alt="" class="img-output">
                                </div>
                            <?php } ?>
                            <input type="file" name="thumbnail" id="imageUpload" style="display: <?php if (isset($video)) { ?> block <?php } else { ?> none <?php } ?>;" class="form-control">
                            <?php if (!isset($video)) { ?>
                                <label class="btn juna-my-button mb-4" for="imageUpload" aria-describedby="inputGroupFileAddon02" style="margin-top: 2rem;">Choose File</label>
                            <?php } ?>
                        </div>
                        <div class="form-group">
                            @if($page == 1)
                            <small class="float-left title-url"></small>
                            <a href="#" class="badge badge-warning rounded float-right mb-3" data-toggle="modal" data-target="#modal-url">URL Produk</a>
                            @endif
                            <input type="text" name="title" id="title" class="form-control" <?php if ($page == 1) echo 'readonly' ?> required placeholder="@if($page != 1) Title @else URL @endif">
                        </div>
                        @if($deskripsi == 'on')
                        <div class="form-group">
                            <textarea class="form-control" id="deskripsi" name="deskripsi" placeholder="Masukan Deskripsi"></textarea>
                        </div>
                        @endif
                        <div class="form-group text-right">
                            <button class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('modal')
<!-- url -->
<div class="modal fade" id="modal-url">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title small"><strong>Tambah url</strong></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-0">
                <table class="table table-striped table-content-middle">
                    <thead>
                        <tr>
                            <th>Thumbnail</th>
                            <th>Nama</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($produk as $val)
                        <tr>
                            <td><img src="{{ asset($val->thumbnail) }}" alt="thumbnail" class="img-banner-data"></td>
                            <td>{{ $val->nama }}</td>
                            <td><a href="#" onclick="setURLToInput()" data-link="<?= route('detail', Illuminate\Support\Facades\Crypt::encrypt($val->id)) ?>" data-title="{{ $val->nama }}" class="badge badge-primary btn-add-url" data-dismiss="modal"><i class="fa fa-plus"></i> Tambah</a></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="modal-footer justify-content-between bg-primary">
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endsection