Ghigha_store/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (isset(Auth::user()->name)) {
        return redirect()->route('admin.home');
    } else {
        return redirect()->route('home');
    }
});

Auth::routes();

Route::get('/home', 'Front\FrontController@index')->name('home');
Route::get('/detail/{id}', 'Front\FrontController@detailProduk')->name('detail');
Route::get('/produk/{search?}', 'Front\FrontController@produk')->name('produk');

// get produk by kategori
Route::get('/produk/get_produk/{kategori_id}', 'Admin\ProdukController@getProduk');
Route::get('/getImageMore/{produk_id}', 'Admin\ProdukController@getImageMore')->name('getImageMore');


Route::group(['middleware' => 'auth'], function () {
    Route::get('/admin', 'Admin\AdminController@index');
    Route::name('admin.')->group(function () {
        Route::get('/admin/home', 'Admin\AdminController@home')->name('home');
        Route::get('/admin/detail_produk', 'Admin\AdminController@detail_produk')->name('detail_produk');
        Route::get('/admin/produk', 'Admin\AdminController@produk')->name('produk');
        Route::get('/admin/setting', 'Admin\AdminController@setting')->name('setting');

        // Img More
        Route::get('/admin/form/img_more/{produk_id}', 'Admin\ProdukController@img_more')->name('form.img_more');
        Route::post('/admin/form/img_more/store', 'Admin\ProdukController@store_img_more')->name('form.img_more.store');
        Route::get('/admin/form/img_more/del/{id}/{produk_id}', 'Admin\ProdukController@del_img_more')->name('form.img_more.del');

        // Form
        // why
        Route::get('/admin/form/why', 'Admin\FormController@form_why')->name('form.why');
        Route::get('/admin/form/{page}', 'Admin\FormController@index')->name('form');
        Route::post('/admin/form/store/{page}', 'Admin\FormController@store')->name('form.store');
        Route::get('/admin/form/edit/{page}/{id}', 'Admin\FormController@edit')->name('form.edit');
        Route::post('/admin/form/update/{page}/{id}', 'Admin\FormController@update')->name('form.update');
        Route::post('/admin/form/why/store', 'Admin\FormController@store_kelebihan')->name('form.why.store');
        Route::get('/admin/form/delete/{page}/{id}', 'Admin\FormController@delete')->name('form.delete');

        // Populer produk
        Route::get('/admin/produk/populer/{id}', 'Admin\ProdukController@store_populer')->name('produk.populer');
        Route::get('/admin/produk/populer/delete/{id}', 'Admin\ProdukController@delete_populer')->name('produk.populer.delete');

        // Produk
        Route::get('/admin/produk/detail/{id}', 'Admin\ProdukController@detail')->name('produk.detail');
        Route::get('/admin/form/produk/form_produk', 'Admin\ProdukController@index')->name('form.produk.form_produk');
        Route::get('/admin/form/produk/form_edit/{id}', 'Admin\ProdukController@form_edit')->name('form.produk.form_edit');
        Route::post('/admin/form/produk/store', 'Admin\ProdukController@store')->name('form.produk.store');
        Route::post('/admin/form/produk/edit/{id}', 'Admin\ProdukController@proses_edit')->name('form.produk.edit');
        Route::get('/admin/form/produk/delete/{id}', 'Admin\ProdukController@delete')->name('form.produk.delete');


        // Setting
        Route::post('/admin/setting/store_nohp', 'Admin\SettingController@store_nohp')->name('setting.store_nohp');
        Route::post('/admin/setting/store_kategori', 'Admin\SettingController@store_kategori')->name('setting.store_kategori');
        Route::post('/admin/setting/edit_kategori/{id}', 'Admin\SettingController@edit_kategori')->name('setting.edit_kategori');
        Route::get('/admin/setting/hapus_kategori/{id}', 'Admin\SettingController@hapus_kategori')->name('setting.hapus_kategori');
        Route::post('/admin/setting/store_alamat', 'Admin\SettingController@store_alamat')->name('setting.store_alamat');
        Route::post('/admin/setting/store_sosmed', 'Admin\SettingController@store_sosmed')->name('setting.store_sosmed');
    });
});

Ghigha_store/resources/views/admin/home.blade.php
@extends('layouts.admin_template')
@section('content')
<div class="container-fluid pb-4 banner">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="mt-4 mb-0">Banner Iklan</h1>
            <small>Iklan produk dengan banner</small>
            <div class="card text-white mt-4">
                <div class="card-header bg-primary py-1 px-3">
                    <small>Beri judul jika ada</small>
                    <div class="float-right">
                        <a href="{{ route('admin.form', Crypt::encrypt('1')) }}" class="badge badge-primary"><i class="fa fa-plus"></i> Tambah</a>
                    </div>
                </div>
                <div class="card-body bg-white table-responsive px-0 pt-0">
                    <table class="table table-striped text-center table-content-middle" id="dataTable2">
                        <thead>
                            <tr>
                                <th>Thumbnail</th>
                                <th>URL</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($banner as $val)
                            <tr>
                                <td>
                                    <a href="{{ asset($val->thumbnail) }}" type="_blank">
                                        <img src="{{ asset($val->thumbnail) }}" alt="thumbnail" class="img-banner-data">
                                    </a>
                                </td>
                                <td>{{ substr($val->title, 0, 30) . '...' }}</td>
                                <td>
                                    <a href="{{ route('admin.form.edit', [Crypt::encrypt('1'), Crypt::encrypt($val->id)]) }}" class="badge badge-warning"><i class="fa fa-pen"></i> Edit</a>
                                    <a href="{{ route('admin.form.delete', [Crypt::encrypt('1'), Crypt::encrypt($val->id)]) }}" class="badge badge-danger"><i class="fa fa-trash"></i> Hapus</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between bg-primary">
                    <!-- <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div> -->
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Terpopuler -->
<div class="container-fluid border-top pb-4 terpopuler" style="background-color: #F5F5F5;">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="mt-4 mb-0">Terpopuler</h1>
            <small>Berikan maximal tiga (3) produk yang paling populer</small>
            <div class="card text-white mt-4">
                <div class="card-header bg-primary py-1 px-3">
                    <small>Beri judul jika ada</small>
                    <?php if ($populer->count() < 3) : ?>
                        <div class="float-right">
                            <a href="#" class="badge badge-primary" data-toggle="modal" data-target="#modal-terpopuler"><i class="fa fa-plus"></i> Tambah</a>
                        </div>
                    <?php endif ?>
                </div>
                <div class="card-body bg-white table-responsive px-0 pt-0">
                    <table class="table table-striped text-center table-content-middle" id="dataTable2">
                        <thead>
                            <tr>
                                <th>Thumbnail</th>
                                <th>Nama</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($populer as $val)
                            <tr>
                                <td>
                                    <img src="{{ asset($val->produk->thumbnail) }}" alt="thumbnail" class="img-banner-data">
                                </td>
                                <td>{{ $val->produk->nama }}</td>
                                <td><a href="{{ route('admin.produk.populer.delete', Crypt::encrypt($val->id)) }}" class="badge badge-danger"><i class="fa fa-trash"></i> Hapus</a></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between bg-primary">
                    <!-- <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div> -->
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Galeri -->
<div class="container-fluid border-top pb-4 galeri">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="mt-4 mb-0">Galeri</h1>
            <small>Berikan bentuk dan style produk dalam galeri</small>
            <div class="card text-white mt-4">
                <div class="card-header bg-primary py-1 px-3">
                    <small>Beri judul jika ada</small>
                    <div class="float-right">
                        <a href="{{ route('admin.form', Crypt::encrypt('3')) }}" class="badge badge-primary"><i class="fa fa-plus"></i> Tambah</a>
                    </div>
                </div>
                <div class="card-body bg-white table-responsive px-0 pt-0">
                    <table class="table table-striped text-center table-content-middle" id="dataTable2">
                        <thead>
                            <tr>
                                <th>Thumbnail</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($galeri as $val)
                            <tr>
                                <td>
                                    <img src="{{ asset($val->thumbnail) }}" alt="thumbnail" class="img-banner-data">
                                </td>
                                <td>{{ $val->title }}</td>
                                <td>{{ $val->deskripsi }}</td>
                                <td>
                                    <a href="{{ route('admin.form.edit', [Crypt::encrypt('3'), Crypt::encrypt($val->id)]) }}" class="badge badge-warning"><i class="fa fa-pen"></i> Edit</a>
                                    <a href="{{ route('admin.form.delete', [Crypt::encrypt('3'), Crypt::encrypt($val->id)]) }}" class="badge badge-danger"><i class="fa fa-trash"></i> Hapus</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between bg-primary">
                    <!-- <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div> -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('modal')
<!-- Terpopuler -->
<div class="modal fade" id="modal-terpopuler">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title small"><strong>Tambah Terpopuler</strong></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-0">
                <table class="table table-striped table-content-middle">
                    <thead>
                        <tr>
                            <th>Thumbnail</th>
                            <th>Nama</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($terpopuler as $val)
                        <tr>
                            <td><img src="{{ asset($val->thumbnail) }}" alt="thumbnail" class="img-banner-data"></td>
                            <td>{{ $val->nama }}</td>
                            <td><a href="{{ route('admin.produk.populer', Crypt::encrypt($val->id)) }}" class="badge badge-primary"><i class="fa fa-plus"></i> Tambah</a></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="modal-footer justify-content-between bg-primary">
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endsection

Ghigha_store/resources/views/admin/produk.blade.php
@extends('layouts.admin_template')
@section('content')
<div class="container-fluid pb-4 produk">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="mt-4 mb-0">Produk</h1>
            <small>Tambahkan produk anda dengan jalas</small>
            <div class="card text-white mt-4">
                <div class="card-header bg-primary">
                    <div class="float-right">
                        <a href="{{ route('admin.form.produk.form_produk') }}" class="badge badge-primary"><i class="fa fa-plus"></i> Tambah</a>
                    </div>
                </div>
                <div class="card-body bg-white table-responsive px-0 pt-1">
                    <table class="table table-striped table-content-middle" id="dataTable2">
                        <thead>
                            <tr>
                                <th>Thumbnail</th>
                                <th>Nama</th>
                                <th>Harga</th>
                                <th>Diskon</th>
                                <th>Harga Diskon</th>
                                <th>Kategori</th>
                                <th>Deskripsi</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($produk as $val)
                            <tr>
                                <td><img src="{{ asset($val->thumbnail) }}" alt="thumbnail" class="img-banner-data"></td>
                                <td>{{ $val->nama }}</td>
                                <td>Rp {{ number_format($val->harga, 0, ',', '.') }}</td>
                                <td>{{ $val->diskon }}%</td>
                                <td>Rp {{ number_format(round($val->harga - ($val->diskon / 100 * $val->harga)), 0, ',', '.') }}</td>
                                <td>{{ $val->kategori->kategori }}</td>
                                <td>{{ substr($val->deskripsi, 3, 20) . '...' }}</td>
                                <td>
                                    <a href="{{ route('admin.produk.detail', Crypt::encrypt($val->id)) }}" class="badge badge-primary"><i class="fa fa-eye"></i> Detail</a>
                                    <a href="{{ route('admin.form.produk.delete', Crypt::encrypt($val->id)) }}" class="badge badge-danger"><i class="fa fa-trash"></i> Hapus</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between bg-primary">
                    <!-- <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div> -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Ghigha_store/resources/views/admin/setting.blade.php
@extends('layouts.admin_template')
@section('content')
<div class="container-fluid pb-4 banner">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="mt-4 mb-0">Setting</h1>
            <small>Semua Penting, data tambahan untuk kebutuhan</small>
            <div class="row">
                <div class="col-lg-6">
                    <div class="card text-white mt-4">
                        <div class="card-header bg-primary py-1 px-3">
                            <small>No Telepon</small>
                        </div>
                        <div class="card-body bg-white">
                            <form action="{{ route('admin.setting.store_nohp') }}" method="post">
                                @csrf
                                <div class="input-group">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-primary" type="button"><i class="fab fa-whatsapp"></i></button>
                                    </div>
                                    <input class="form-control" type="number" name="no_telepon" placeholder="No Telepon" value="{{ $no_hp->no_telepon }}" aria-label="no_hp" aria-describedby="basic-addon2" />
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-warning" type="button"><i class="fas fa-pen"></i></button>
                                    </div>
                                </div>
                                <small class="text-dark">Masukan nomor dan click icon untuk mengubah</small>
                            </form>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between bg-primary">
                            <!-- <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div> -->
                        </div>
                    </div>
                    <!-- Kategori -->
                    <div class="card text-white mt-4">
                        <div class="card-header bg-primary py-1 px-3">
                            <small>Kategori</small>
                            <div class="float-right">
                                <a href="#" class="badge badge-primary insert-kategori" data-toggle="modal" data-target="#modal-kategori"><i class="fa fa-plus"></i> Tambah</a>
                            </div>
                        </div>
                        <div class="card-body bg-white table-responsive px-0 pt-0">
                            <table class="table table-striped text-center" id="dataTable2">
                                <thead>
                                    <tr>
                                        <th>Kategori</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($kategori as $val)
                                    <tr>
                                        <td>{{ $val->kategori }}</td>
                                        <td>
                                            <a href="#" class="badge badge-warning edit-kategori" data-toggle="modal" data-target="#modal-kategori" data-url="{{ route('admin.setting.edit_kategori', Crypt::encrypt($val->id)) }}" data-value="{{ $val->kategori }}"><i class="fa fa-pen"></i> Edit</a>
                                            <a href="{{ route('admin.setting.hapus_kategori', Crypt::encrypt($val->id)) }}" class="badge badge-danger"><i class="fa fa-trash"></i> Hapus</a>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between bg-primary">
                            <!-- <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div> -->
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card text-white mt-4">
                        <form action="{{ route('admin.setting.store_alamat') }}" method="post">
                            @csrf
                            <div class="card-header bg-primary py-1 px-3">
                                <small>Alamat</small>
                                <div class="float-right">
                                    <button type="submit" class="badge badge-primary border-0"><i class="fa fa-pen"></i> Simpan</button>
                                </div>
                            </div>
                            <div class="card-body bg-white">
                                <div class="editor">
                                    <textarea class="form-control" id="alamat" name="alamat">{{ $alamat->alamat }}</textarea>
                                </div>
                                <small class="text-dark">Masukan alamat dan click tombol simpan untuk mengubah</small>
                            </div>
                        </form>
                        <div class="card-footer d-flex align-items-center justify-content-between bg-primary">
                            <!-- <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div> -->
                        </div>
                    </div>

                    <!-- Sosmed -->
                    <div class="card text-white mt-4">
                        <div class="card-header bg-primary py-1 px-3">
                            <small>Link Sosial media</small>
                        </div>
                        <div class="card-body bg-white">
                            <form action="{{ route('admin.setting.store_sosmed') }}" method="post">
                                @csrf
                                <small class="text-dark">Facebook</small>
                                <div class="input-group">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-primary" type="button"><i class="fab fa-facebook"></i></button>
                                    </div>
                                    <input class="form-control" type="text" name="facebook" placeholder="..." value="@if(isset($sosmed->facebook)){{ $sosmed->facebook }}@endif" aria-label="sosmed" aria-describedby="basic-addon2" />
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-warning" type="button"><i class="fas fa-pen"></i></button>
                                    </div>
                                </div>
                            </form>

                            <form action="{{ route('admin.setting.store_sosmed') }}" method="post">
                                @csrf
                                <small class="text-dark">Twitter</small>
                                <div class="input-group">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-primary" type="button"><i class="fab fa-twitter"></i></button>
                                    </div>
                                    <input class="form-control" type="text" name="twitter" placeholder="..." value="@if(isset($sosmed->twitter)){{ $sosmed->twitter }}@endif" aria-label="sosmed" aria-describedby="basic-addon2" />
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-warning" type="button"><i class="fas fa-pen"></i></button>
                                    </div>
                                </div>
                            </form>

                            <form action="{{ route('admin.setting.store_sosmed') }}" method="post">
                                @csrf
                                <small class="text-dark">Instagram</small>
                                <div class="input-group">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-primary" type="button"><i class="fab fa-instagram"></i></button>
                                    </div>
                                    <input class="form-control" type="text" name="instagram" placeholder="..." value="@if(isset($sosmed->instagram)){{ $sosmed->instagram }}@endif" aria-label="sosmed" aria-describedby="basic-addon2" />
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-warning" type="button"><i class="fas fa-pen"></i></button>
                                    </div>
                                </div>
                            </form>

                            <form action="{{ route('admin.setting.store_sosmed') }}" method="post">
                                @csrf
                                <small class="text-dark">Youtube</small>
                                <div class="input-group">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-primary" type="button"><i class="fab fa-youtube"></i></button>
                                    </div>
                                    <input class="form-control" type="text" name="youtube" placeholder="..." value="@if(isset($sosmed->youtube)){{ $sosmed->youtube }}@endif" aria-label="sosmed" aria-describedby="basic-addon2" />
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-warning" type="button"><i class="fas fa-pen"></i></button>
                                    </div>
                                </div>

                                <small class="text-dark">Masukan link dan click icon pen untuk mengubah</small>
                            </form>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between bg-primary">
                            <!-- <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('modal')
<div class="modal fade" id="modal-kategori">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title title-kategori small"><strong>Tambah Kategori</strong></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="post">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <small>Kategori</small>
                        <input type="text" class="form-control" name="kategori" id="kategori" placeholder="...">
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn border" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-primary btn-simpan">Simpan</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endsection
@section('myjs')
<script>
    $(document).ready(function() {
        $('.insert-kategori').on('click', function() {
            $('#modal-kategori .title-kategori').html('Tambah Kategori');
            $('#modal-kategori .btn-simpan').removeClass('bg-warning');
            $('#modal-kategori .btn-simpan').addClass('bg-primary');
            $('#modal-kategori .btn-simpan').removeClass('text-dark');
            $('#modal-kategori .btn-simpan').addClass('text-light');
            $('#modal-kategori form').attr('action', '<?= route('admin.setting.store_kategori') ?>');
        });
        $('.edit-kategori').on('click', function() {
            var url = $(this).data('url');
            var value = $(this).data('value');

            $('#modal-kategori .title-kategori').html('Edit Kategori');
            $('#modal-kategori .btn-simpan').removeClass('bg-primary');
            $('#modal-kategori .btn-simpan').addClass('bg-warning');
            $('#modal-kategori .btn-simpan').addClass('text-dark');
            $('#modal-kategori .btn-simpan').addClass('border-0');
            $('#modal-kategori form input[name=kategori]').val(value);
            $('#modal-kategori form').attr('action', url);
        });
    });
</script>
@endsection